/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.4/userguide/building_java_projects.html in the Gradle documentation.
 */

/*
 * https://teavm.org/docs/intro/getting-started.html（2026/10/13時点）
 * 上記サイトを基に作成。ただし、ドキュメントは Groovy の書き方で、このプロジェクトは Kotlin
 * https://zenn.dev/suwash/articles/gradle_20250905
 * 上記サイトは参考までに
 */

plugins {
    java
    war
    id("org.teavm") version "0.16.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(teavm.libs.jsoApis)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

teavm {
    all {
        mainClass = "org.example.App"
    }
    wasmGC {
        addedToWebApp = true
        targetFileName = "eig_example.wasm"
    }
}

